# Generated by Django 3.1.5 on 2021-01-05 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_recipeingredientunit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredientunit",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="app.recipe",
            ),
        ),
    ]
